name: Build

on:
  push:
      branches:
          - master
          - main
  pull_request:
      branches:
          - "*"
  release:
    types: [created]

jobs:

  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        shell: pwsh
        run: ./build.ps1

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-tool-pacakge
          path: publish/packages/*.nupkg
          retention-days: 1

      - name: Publish to nuget
        if: ${{ github.event_name == 'release' }}
        shell: pwsh
        run: |
          dotnet nuget push 'publish/packages/*.nupkg' --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"  --skip-duplicate
