name: Build

on:
  push:
      branches:
          - master
          - main
  pull_request:
      branches:
          - "*"
  release:
    types: [created]

jobs:

  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        shell: pwsh
        run: ./build.ps1

      - name: Upload binaries to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: publish/win/KubeConnect.exe
          asset_name: 'KubeConnect.exe'
          tag: ${{ github.ref }}
          overwrite: true

      - name: Publish nuget tools
        if: ${{ github.event_name == 'release' }}
        shell: pwsh
        run: |
          $pck = "$(Get-ChildItem .\publish\tool\*.nupkg | foreach {$_.FullName } | select -First 1)"
          dotnet nuget push $pck --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-binary
          path: publish/win/KubeConnect.exe
          retention-days: 1

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-tool-pacakge
          path: publish/tool/*.nupkg
          retention-days: 1